### ISSUE TITLE
after first login, the VM list does not refresh automatically

### ISSUE THREAD

**Issue by jelkosz** [oVirt/moVirt#196] opened 2016-09-22 06:02 UTC

**Comment by suomiy** [comment] 2016-10-12 23:46
This happens very seldom on my setup and I could not find the cause/conditions of that.

**Comment by shiramax** [comment] 2016-10-31 08:26
I can reproduce it 
1. start a vm from my PC
2. see that there is no change in the app after 10 minutes, only if i refresh it manually.

**Comment by jelkosz** [comment] 2016-11-01 07:36
@shiramax this is a different issue. What you see is the generic issue with synced accounts in android. Android does not make your app poll too often, only once in a while which depends on tons of things like battery level, if you are connected to charger, if the device has been moving recently, time in day etc. But one way or the other, it is synced just couple of times a day.

If you want to enforce faster syncs, in moVirt enable Settings->Periodic Sync and than under it in Sync Interval set some value. But if you will set low value, like once a minute, it will eat up your battery quite fast...

**Comment by suomiy** [comment] 2017-06-15 16:23
sync problems like this should be fixed with the 2.0 release

**Closed by suomiy** 2017-06-15 16:23 UTC
Labels: bug
