### ISSUE TITLE
in oVirt 4.1.0, The events in VM doesn't appear

### ISSUE THREAD

**Issue by shiramax** [oVirt/moVirt#228] opened 2016-12-01 14:41 UTC
version: oVirt Engine Version: 4.1.0-0.0.master.20161120231325.gitba51756.el7.centos

The events doesn't appear in the vm Events tab, (not after sync too.. )
if i press on 'Clear Local Events', and then sync -> if o go to the events tab in the VM, the events appear.

**Comment by suomiy** [comment] 2016-12-02 15:57
This is caused by maximum limit of events and/or events search query. The events sync in vm, hosts, etc. fires only global event sync. So events of some vms, etc. are over the limit.

This could be fixed by fetching predetermined number (another entry in settings?) of events in VmActivity.

any other ideas?

**Comment by shiramax** [comment] 2016-12-15 08:16
checking this on movirt version 1.7, and the events doesn't appear even after 'Clear Local Events' and sync.

**Closed** 2017-06-15 10:46 UTC
